# Generated by Django 4.1.6 on 2023-02-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=600)),
                ('matricula', models.IntegerField(blank=True, default=None, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('ddd', models.CharField(default='19', max_length=2)),
                ('whatsapp', models.CharField(default='997898757', max_length=12)),
                ('e_mail', models.EmailField(max_length=400, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=255)),
                ('e_mail', models.EmailField(max_length=400, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('excluido', models.BooleanField(default=False)),
                ('colaborador_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emails_controller.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=255)),
                ('assunto', models.CharField(max_length=255)),
                ('enviado', models.BooleanField(default=False)),
                ('tentativas_envio', models.IntegerField(default=0)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails_controller.contato')),
            ],
        ),
    ]
