# Generated by Django 4.1.6 on 2023-03-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
                ('cabecalho', models.CharField(max_length=255)),
                ('rodape', models.CharField(max_length=255)),
                ('conteudo_A', models.TextField()),
                ('conteudo_B', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeradorTarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('por_vendedor', models.BooleanField(default=True)),
                ('por_contato', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails_controller.contato')),
                ('conteudo_email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emails_controller.conteudoemail')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emails_controller.colaborador')),
            ],
        ),
    ]
