# Generated by Django 4.1.6 on 2023-03-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0003_alter_geradortarefas_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geradortarefas',
            old_name='contact',
            new_name='contato',
        ),
    ]
