# Generated by Django 4.1.6 on 2023-03-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0004_rename_contact_geradortarefas_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='geradortarefas',
            name='todos_contatos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task_envio',
            name='conteudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails_controller.conteudoemail'),
        ),
        migrations.AlterField(
            model_name='geradortarefas',
            name='contato',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
