# Generated by Django 4.1.6 on 2023-03-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0005_geradortarefas_todos_contatos_task_envio_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoemail',
            name='titulo',
            field=models.CharField(default="'", max_length=500),
        ),
    ]
