# Generated by Django 4.1.6 on 2023-04-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0006_conteudoemail_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='geradortarefas',
            name='tarefas_criadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='geradortarefas',
            name='todos_contatos',
            field=models.BooleanField(default=False),
        ),
    ]
