# Generated by Django 4.1.6 on 2024-02-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0007_geradortarefas_tarefas_criadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='pesquisa_satisfacao',
            field=models.BooleanField(default=False),
        ),
    ]
