# Generated by Django 4.1.6 on 2024-02-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0008_contato_pesquisa_satisfacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='geradortarefas',
            name='pesquisa_qualidade',
            field=models.BooleanField(default=False),
        ),
    ]
