# Generated by Django 4.1.6 on 2024-02-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0009_geradortarefas_pesquisa_qualidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geradortarefas',
            old_name='pesquisa_qualidade',
            new_name='pesquisa_satisfacao',
        ),
    ]
