# Generated by Django 4.2.7 on 2025-07-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0010_rename_pesquisa_qualidade_geradortarefas_pesquisa_satisfacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoemail',
            name='foto_a',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='conteudoemail',
            name='foto_b',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='conteudoemail',
            name='foto_c',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='conteudoemail',
            name='foto_d',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='conteudoemail',
            name='foto_e',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='conteudoemail',
            name='foto_f',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='geradortarefas',
            name='pesquisa_satisfacao',
            field=models.BooleanField(default=False, verbose_name='Pesquisa de Satisfação'),
        ),
    ]
