# Generated by Django 4.2.7 on 2025-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0011_conteudoemail_foto_a_conteudoemail_foto_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudoemail',
            name='foto_f',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images'),
        ),
    ]
