# Generated by Django 4.2.7 on 2025-07-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0012_alter_conteudoemail_foto_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudoemail',
            name='cabecalho',
        ),
        migrations.RemoveField(
            model_name='conteudoemail',
            name='rodape',
        ),
        migrations.AddField(
            model_name='conteudoemail',
            name='pre_imagens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conteudoemail',
            name='titulo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
