# Generated by Django 4.2.7 on 2025-07-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0013_remove_conteudoemail_cabecalho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudoemail',
            name='pre_imagens',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
