# Generated by Django 4.2.7 on 2025-07-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0014_alter_conteudoemail_pre_imagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudoemail',
            name='foto_a',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images'),
        ),
        migrations.AlterField(
            model_name='conteudoemail',
            name='foto_b',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images'),
        ),
        migrations.AlterField(
            model_name='conteudoemail',
            name='foto_c',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images'),
        ),
        migrations.AlterField(
            model_name='conteudoemail',
            name='foto_d',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images'),
        ),
        migrations.AlterField(
            model_name='conteudoemail',
            name='foto_e',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images'),
        ),
    ]
