# Generated by Django 4.2.7 on 2025-09-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0015_alter_conteudoemail_foto_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoemail',
            name='tipo_email',
            field=models.CharField(choices=[('6_fotos', '6 Fotos'), ('sem_foto', 'Sem Fotos')], default='6_fotos', max_length=10),
        ),
    ]
