# Generated by Django 4.2.7 on 2026-05-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0016_conteudoemail_tipo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudoemail',
            name='tipo_email',
            field=models.CharField(choices=[('6_fotos', '6 Fotos'), ('sem_foto', 'Sem Fotos'), ('apresentacao', 'Apresentação')], default='6_fotos', max_length=20),
        ),
    ]
