# Generated by Django 4.2.7 on 2026-06-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0020_add_agendamento_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_envio',
            name='contato_desativado',
            field=models.BooleanField(default=False),
        ),
    ]
