# Generated by Django 4.2.7 on 2026-06-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0021_add_contato_desativado_task_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudoemail',
            name='tipo_email',
            field=models.CharField(choices=[('6_fotos', '6 Fotos'), ('sem_foto', 'Sem Fotos'), ('apresentacao', 'Apresentação'), ('padrao_a_4', 'Padrão A - 4 Fotos'), ('padrao_a_6', 'Padrão A - 6 Fotos'), ('padrao_b_4', 'Padrão B - 4 Fotos'), ('padrao_b_6', 'Padrão B - 6 Fotos')], default='6_fotos', max_length=20),
        ),
    ]
