# Generated by Django 4.2.7 on 2026-06-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_controller', '0022_add_padrao_b_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoContatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='importacoes/', verbose_name='Planilha Excel')),
                ('simulacao', models.BooleanField(default=False, verbose_name='Simulação (não salva alterações)')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('sucesso', 'Sucesso'), ('parcial', 'Parcial (com erros)'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Importação de Contatos',
                'verbose_name_plural': 'Importações de Contatos',
            },
        ),
    ]
